import { Dimensions } from "react-native";

export const SIZES = {
  MARGING_X_SMALL: 4,
  MARGING_SMALL: 8,
  MARGING_REGULAR: 12,
  MARGING_LARGE: 16,
  MARGING_X_LARGE: 20,
  MARGING_XX_LARGE: 32,
  PADDING_X_SMALL: 4,
  PADDING_SMALL: 8,
  PADDING_REGULAR: 12,
  PADDING_LARGE: 16,
  PADDING_X_LARGE: 20,
  PADDING_XX_LARGE: 32,
  RADIUS_SMALL: 8,
  RADIUS_REGULAR: 16,
  RADIUS_LARGE: 32,
  ICON_X_SMALL: 12,
  ICON_SMALL: 16,
  ICON_REGULAR: 24,
  ICON_LARGE: 32,
  TAB_SIZE: Dimensions.get("screen").height * 0.1,
  SCREEN_WIDTH: Dimensions.get("screen").width,
  SCREEN_HEIGHT: Dimensions.get("screen").height,
};
